#!/bin/env bash

setup_docker() {

	apt install \
		apt-transport-https \
		ca-certificates \
		curl \
		gnupg \
		lsb-release -y

	curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

	echo \
		"deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
		$(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

	apt update
	apt remove docker docker-engine docker.io containerd runc
	apt install docker-ce docker-ce-cli containerd.io

}
